// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/BarChart.vue')['default']
    BaseChart: typeof import('./components/BaseChart.vue')['default']
    DemoChart: typeof import('./components/LineChart.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
  }
}

export {}
